CREATE TABLE Users(Email VARCHAR(32) PRIMARY KEY, Password VARCHAR(32) NOT NULL, DeviceId VARCHAR(32) UNIQUE);

CREATE TABLE Experiences(Id VARCHAR(36) PRIMARY KEY, Name VARCHAR(32) NOT NULL, User VARCHAR(32) NOT NULL, NWLongitude REAL NOT NULL, NWLatitude REAL NOT NULL, SELongitude REAL NOT NULL, SELatitude REAL NOT NULL, FOREIGN KEY(User) REFERENCES Users(Email));

CREATE TABLE Tracks(Name VARCHAR(32) PRIMARY KEY);

CREATE TABLE Checkpoints(Id INTEGER PRIMARY KEY AUTO_INCREMENT, TrackName VARCHAR(32) NOT NULL, Longitude REAL NOT NULL, Latitude REAL NOT NULL, Idx INTEGER NOT NULL, FOREIGN KEY(TrackName) REFERENCES Tracks(Name) ON DELETE CASCADE);

CREATE TABLE Telemetries(Id INTEGER PRIMARY KEY AUTO_INCREMENT, TrackName VARCHAR(32) NOT NULL, FOREIGN KEY(TrackName) REFERENCES Tracks(Name) ON DELETE CASCADE);

CREATE TABLE TelemetryEvents(Id INTEGER PRIMARY KEY AUTO_INCREMENT, TelemetryId INTEGER NOT NULL, Date TIMESTAMP NOT NULL, FOREIGN KEY(TelemetryId) REFERENCES Telemetries(Id) ON DELETE CASCADE);

CREATE TABLE ExperienceTracks(Id INTEGER PRIMARY KEY AUTO_INCREMENT, ExperienceId VARCHAR(36) NOT NULL, TrackName VARCHAR(32) NOT NULL, FOREIGN KEY(ExperienceId) REFERENCES Experiences(Id), FOREIGN KEY(TrackName) REFERENCES Tracks(Name) ON DELETE CASCADE);

CREATE TABLE ExperienceUserPoints(Id INTEGER PRIMARY KEY AUTO_INCREMENT, ExperienceId VARCHAR(36) NOT NULL, Name VARCHAR(32) NOT NULL, Longitude REAL NOT NULL, Latitude REAL NOT NULL, FOREIGN KEY(ExperienceId) REFERENCES Experiences(Id));

CREATE TABLE POIs(Name VARCHAR(32) PRIMARY KEY, Longitude REAL NOT NULL, Latitude REAL NOT NULL, Type VARCHAR(32) NOT NULL);

CREATE TABLE ExperiencePOIs(Id INTEGER PRIMARY KEY AUTO_INCREMENT, ExperienceId VARCHAR(36) NOT NULL, POIName VARCHAR(32) NOT NULL, FOREIGN KEY(ExperienceId) REFERENCES Experiences(Id), FOREIGN KEY(POIName) REFERENCES POIs(Name));

CREATE TABLE Lakes(Name VARCHAR(32) PRIMARY KEY);

CREATE TABLE LakePoints(Id INTEGER PRIMARY KEY AUTO_INCREMENT, LakeName VARCHAR(32) NOT NULL, Longitude REAL NOT NULL, Latitude REAL NOT NULL, Idx INTEGER NOT NULL, FOREIGN KEY(LakeName) REFERENCES Lakes(Name));

CREATE TABLE Rivers(Name VARCHAR(32) PRIMARY KEY);

CREATE TABLE RiverPoints(Id INTEGER PRIMARY KEY AUTO_INCREMENT, RiverName VARCHAR(32) NOT NULL, Longitude REAL NOT NULL, Latitude REAL NOT NULL, Idx INTEGER NOT NULL, FOREIGN KEY(RiverName) REFERENCES Rivers(Name));

CREATE TABLE Paths(Name VARCHAR(32) PRIMARY KEY);

CREATE TABLE PathPoints(Id INTEGER PRIMARY KEY AUTO_INCREMENT, PathName VARCHAR(32) NOT NULL, Longitude REAL NOT NULL, Latitude REAL NOT NULL, Idx INTEGER NOT NULL, FOREIGN KEY(PathName) REFERENCES Paths(Name));

CREATE TABLE EmergencyContacts(Id INTEGER PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(32) NOT NULL, Number VARCHAR(32) NOT NULL, NWLongitude REAL NOT NULL, NWLatitude REAL NOT NULL, SELongitude REAL NOT NULL, SELatitude REAL NOT NULL);

CREATE TABLE WeatherForecasts(Id INTEGER PRIMARY KEY AUTO_INCREMENT, MTemperature REAL NOT NULL, ATemperature REAL NOT NULL, NTemperature REAL NOT NULL,  Date TIMESTAMP NOT NULL, MForecast VARCHAR(32) NOT NULL, AForecast VARCHAR(32) NOT NULL, NForecast VARCHAR(32) NOT NULL, NWLongitude REAL NOT NULL, NWLatitude REAL NOT NULL, SELongitude REAL NOT NULL, SELatitude REAL NOT NULL);

CREATE TABLE ElevationRect(Id INTEGER PRIMARY KEY AUTO_INCREMENT, Height INTEGER NOT NULL, NWLongitude REAL NOT NULL, NWLatitude REAL NOT NULL, SELongitude REAL NOT NULL, SELatitude REAL NOT NULL);

CREATE TABLE SyncList(Id INTEGER PRIMARY KEY AUTO_INCREMENT, User VARCHAR(32) NOT NULL, ExperienceId VARCHAR(36) NOT NULL, FOREIGN KEY(ExperienceId) REFERENCES Experiences(Id), FOREIGN KEY(User) REFERENCES Users(Email));
